#include "\pjhq\patch_trfukaf\addons\main\armor_macros.hpp"
#include "\pjhq\patch_trfukaf\addons\main\placeable_macros.hpp"

class CfgPatches {
	class PJHQ_Patch_TRFUKAF {
		name = "PJHQ Patches - TRF UKAF";
		author = "N. Home";
		requiredVersion = 2.18;
		requiredAddons[] = {"PJHQ_Patch_TRFUKAF_Main", "TRF_UKAF"};
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
	};
};

class CfgWeapons {
	class ItemCore;
	class HeadgearItem;
	class VestItem;

	PJHQ_PATCH_HELMET_ARMOR(TRF_BATLSKIN_REVISION_UN);
	PJHQ_PATCH_HELMET_ARMOR(TRF_BATLSKIN_REVISION_CREW);
	PJHQ_PATCH_HELMET_ARMOR(TRF_BATLSKIN_REVISION_CREW_SCRIM);
	PJHQ_PATCH_HELMET_ARMOR(TRF_BATLSKIN_REVISION);
	PJHQ_PATCH_HELMET_ARMOR(TRF_BATLSKIN_REVISION_IR);
	PJHQ_PATCH_HELMET_ARMOR(TRF_BATLSKIN_REVISION_NETTING);
	PJHQ_PATCH_HELMET_ARMOR(TRF_BATLSKIN_REVISION_NETTING_IR);
	PJHQ_PATCH_HELMET_ARMOR(TRF_BATLSKIN_REVISION_SCRIM_OAK);

	PJHQ_PATCH_VEST_ARMOR(TRF_STV_Grenadier);
	PJHQ_PATCH_VEST_ARMOR(TRF_STV_Medic);
	PJHQ_PATCH_VEST_ARMOR(TRF_STV_Gunner);
	PJHQ_PATCH_VEST_ARMOR(TRF_STV_Sharpshooter);
	PJHQ_PATCH_VEST_ARMOR(TRF_STV_Crew);
	PJHQ_PATCH_VEST_ARMOR(TRF_STV_Rifleman);
	PJHQ_PATCH_VEST_ARMOR(TRF_STV_Rifleman_2);
	PJHQ_PATCH_VEST_ARMOR(TRF_STV_Rifleman_3);
	PJHQ_PATCH_VEST_ARMOR(TRF_STV_IC);
	PJHQ_PATCH_VEST_ARMOR(TRF_STV_IC_2);
	PJHQ_PATCH_VEST_ARMOR(TRF_STV_IC_3);
};

class CfgVehicles {
	PJHQ_HIDE_PLACEABLE(TRF_PCS_FS_NG_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_PCS_FS_G_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_PCS_HS_NG_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_PCS_HS_G_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_PCS_RS_NG_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_PCS_RS_G_U_TEX);
};
