#include "\pjhq\patch_trfukaf\addons\main\placeable_macros.hpp"

class CfgPatches {
	class PJHQ_Patch_TRFUKAF_CS95_INSIGNIA {
		name = "PJHQ Patches - TRF UKAF CS95 Insignia";
		author = "N. Home";
		requiredVersion = 2.18;
		requiredAddons[] = {"PJHQ_Patch_TRFUKAF_Main", "TRF_UKAF"};
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
	};
};

class CfgVehicles {
	class B_Soldier_base_F;

	PJHQ_HIDE_PLACEABLE(TRF_CS95_1RIF_FS_NG_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_1RIF_FS_G_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_1RIF_HS_NG_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_1RIF_HS_G_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_1RIF_RS_NG_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_1RIF_RS_G_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_2PARA_FS_NG_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_2PARA_FS_G_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_2PARA_HS_NG_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_2PARA_HS_G_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_2PARA_RS_NG_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_2PARA_RS_G_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_3SCOTS_FS_NG_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_3SCOTS_FS_G_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_3SCOTS_HS_NG_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_3SCOTS_HS_G_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_3SCOTS_RS_NG_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_3SCOTS_RS_G_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_MERCIAN_FS_NG_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_MERCIAN_FS_G_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_MERCIAN_HS_NG_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_MERCIAN_HS_G_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_MERCIAN_RS_NG_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_MERCIAN_RS_G_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_1RY_FS_NG_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_1RY_FS_G_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_1RY_HS_NG_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_1RY_HS_G_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_1RY_RS_NG_U_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CS95_1RY_RS_G_U_TEX);
};
