#include "\pjhq\patch_trfukaf\addons\main\armor_macros.hpp"
#include "\pjhq\patch_trfukaf\addons\main\placeable_macros.hpp"

class CfgPatches {
	class PJHQ_Patch_TRFUKAF_SFSG {
		name = "PJHQ Patches - TRF UKAF SFSG";
		author = "N. Home";
		requiredVersion = 2.18;
		requiredAddons[] = {"PJHQ_Patch_TRFUKAF_Main", "TRF_UKAF"};
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
	};
};

class CfgWeapons {
	class ItemCore;
	class HeadgearItem;
	class VestItem;

	PJHQ_PATCH_HELMET_ARMOR(TRF_FAST_SFHC);

	PJHQ_PATCH_VEST_ARMOR(UKAF_C2R_CBAV_SL);
	PJHQ_PATCH_VEST_ARMOR(UKAF_C2R_CBAV_SL_2);
	PJHQ_PATCH_VEST_ARMOR(UKAF_C2R_CBAV_MEDIC);
	PJHQ_PATCH_VEST_ARMOR(UKAF_C2R_CBAV_MARKSMAN);
	PJHQ_PATCH_VEST_ARMOR(UKAF_C2R_CBAV_JTAC);
	PJHQ_PATCH_VEST_ARMOR(UKAF_C2R_CBAV_JTAC_2);
	PJHQ_PATCH_VEST_ARMOR(UKAF_C2R_CBAV_RIFLEMAN);
	PJHQ_PATCH_VEST_ARMOR(UKAF_C2R_CBAV_RIFLEMAN_2);
};

class CfgVehicles {
	class B_Soldier_base_F;

	PJHQ_HIDE_PLACEABLE(TRF_CRYE_G4_B_NG_FS_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CRYE_G4_BLNK_NG_FS_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CRYE_G4_RMC_NG_FS_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CRYE_G4_B_NG_RS_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CRYE_G4_BLNK_NG_RS_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CRYE_G4_RMC_NG_RS_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CRYE_G4_B_G_RS_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CRYE_G4_BLNK_G_RS_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CRYE_G4_RMC_G_RS_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CRYE_G4_RNC_PCU_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CRYE_G4_BLNK_PCU_TEX);
	PJHQ_HIDE_PLACEABLE(TRF_CRYE_G4_RMC_PCU_TEX);
};
