[config.file_type]
options.allow_no_extension = false

[stringtables.usage]
options.ignore_unused = true

[sqf.banned_commands]
options.banned = [
  "spawn", # Scheduled should be avoided whenever possible
  "execVM", # Script files should never be run directly, they should be functions
  "remoteExec", # CBA events should be used for networking
  "addPublicVariableEventHandler", # Alt syntax is broken, we are using main syntax
  "createSoundSource" # Greatly attenuated when in first person and in a vehicle"
]

[sqf.banned_macros]
options.release = ["DEBUG_MODE_FULL", "DISABLE_COMPILE_CACHE"]

[sqf.this_call]
enabled = true

[sqf.undefined]
enabled = true
options.check_orphan_code = true

[sqf.unused]
#enabled = true # many false positives without DEBUG_MODE_FULL
options.check_params = false

[sqf.shadowed]
enabled = false

[sqf.not_private]
enabled = true
