import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { compareConfigs, UNKNOWN_VALUE, type ConfigComparison } from "./lib/config-comparison.ts";

interface AddonPatch {
  directory: string;
  patchName: string;
  displayName: string;
  requiredAddons: string[];
  helmet: string[];
  vest: string[];
  hidden: string[];
}

const root = path.resolve(import.meta.dir, "..");
const addonsRoot = path.join(root, "addons");
const repositoryUrl = "https://github.com/pjhq/addon_patch_trfukaf";

function requireMatch(value: RegExpMatchArray | null, description: string): RegExpMatchArray {
  if (!value) {
    throw new Error(`Could not parse ${description}`);
  }
  return value;
}

function capture(text: string, expression: RegExp, description: string): string {
  const match = requireMatch(text.match(expression), description);
  const value = match[1];
  if (value === undefined) {
    throw new Error(`Parsed ${description} without a value`);
  }
  return value;
}

function macroArguments(config: string, macro: string): string[] {
  return [...config.matchAll(new RegExp(`\\b${macro}\\s*\\(\\s*([A-Za-z0-9_]+)\\s*\\)`, "g"))].map((match) => {
    const value = match[1];
    if (value === undefined) {
      throw new Error(`Parsed ${macro} without a class name`);
    }
    return value;
  });
}

async function readAddons(): Promise<AddonPatch[]> {
  const directories = (await readdir(addonsRoot, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort((left, right) => {
      if (left === "main") return -1;
      if (right === "main") return 1;
      return left.localeCompare(right);
    });

  return Promise.all(
    directories.map(async (directory): Promise<AddonPatch> => {
      const config = await readFile(path.join(addonsRoot, directory, "config.cpp"), "utf8");
      const patchName = capture(config, /class\s+CfgPatches\s*\{\s*class\s+([A-Za-z0-9_]+)/, `${directory} CfgPatches class`);
      const displayName = capture(config, /\bname\s*=\s*"([^"]+)"\s*;/, `${directory} display name`);
      const requiredAddonsBody = capture(config, /\brequiredAddons\[\]\s*=\s*\{([^}]*)\}/, `${directory} requiredAddons`);
      const requiredAddons = [...requiredAddonsBody.matchAll(/"([^"]+)"/g)].map((match) => match[1]).filter((value): value is string => value !== undefined);

      return {
        directory,
        patchName,
        displayName,
        requiredAddons,
        helmet: macroArguments(config, "PJHQ_PATCH_HELMET_ARMOR"),
        vest: macroArguments(config, "PJHQ_PATCH_VEST_ARMOR"),
        hidden: macroArguments(config, "PJHQ_HIDE_PLACEABLE")
      };
    })
  );
}

function markdownValue(value: string): string {
  return value === UNKNOWN_VALUE ? value : `\`${value}\``;
}

function markdownTable(changes: ConfigComparison["helmet"]): string {
  return [
    "| Area | Property | From | To | Baseline status |",
    "| --- | --- | --- | --- | --- |",
    ...changes.map((change) => `| ${change.area} | \`${change.property}\` | ${markdownValue(change.from)} | ${markdownValue(change.to)} | ${change.status} |`)
  ].join("\n");
}

function markdownClassList(label: string, classes: string[]): string {
  if (classes.length === 0) {
    return "";
  }
  return [`**${label} (${classes.length})**`, "", "```text", ...classes, "```", ""].join("\n");
}

function renderReadme(addons: AddonPatch[], changes: ConfigComparison): string {
  const helmets = addons.flatMap((addon) => addon.helmet);
  const vests = addons.flatMap((addon) => addon.vest);
  const hiddenDeclarations = addons.flatMap((addon) => addon.hidden);
  const uniqueHidden = new Set(hiddenDeclarations);
  const duplicateHidden = hiddenDeclarations.length - uniqueHidden.size;
  const patchedAddons = addons.filter((addon) => addon.helmet.length + addon.vest.length + addon.hidden.length > 0);
  const addonSections = addons
    .filter((addon) => addon.helmet.length + addon.vest.length + addon.hidden.length > 0)
    .map((addon) => {
      const requirements = addon.requiredAddons.length === 0 ? "None" : addon.requiredAddons.map((requirement) => `\`${requirement}\``).join(", ");
      return [
        `### ${addon.displayName} (\`${addon.directory}\`)`,
        "",
        `- Config patch: \`${addon.patchName}\``,
        `- Required addons: ${requirements}`,
        "",
        ...[
          markdownClassList("Helmet armor", addon.helmet),
          markdownClassList("Vest armor", addon.vest),
          markdownClassList("Hidden from Eden/Zeus placement", addon.hidden)
        ].filter((part) => part !== "")
      ].join("\n");
    });

  return [
    "<!-- Generated by scripts/generate-docs.ts. Do not edit by hand. -->",
    "# PJHQ Patch - TRF UKAF",
    "",
    "A config-only compatibility and balance patch for TRF UKAF. It normalizes helmet and vest protection and removes soldier gear proxy classes from Eden/Zeus placement without removing equipment from the Arsenal.",
    "",
    "## What It Changes",
    "",
    `- Rebalances **${helmets.length} helmets** and **${vests.length} vests** across ${patchedAddons.filter((addon) => addon.helmet.length + addon.vest.length > 0).length} component patches.`,
    `- Hides **${uniqueHidden.size} unique classes** from Eden/Zeus placement using ${hiddenDeclarations.length} declarations. ${duplicateHidden} PCS proxy classes overlap between the insignia component patches.`,
    "- Changes config values only. This project contains no replacement models, textures, sounds, scripts or event handlers.",
    "- Does not change `scopeArsenal`, so wearable gear remains available in the Arsenal where the source addon exposes it.",
    "- See [Damage And Armor Reference](DAMAGE_INFO.md) for how ammunition and personal armor values interact under vanilla and ACE Medical damage handling.",
    "",
    "## Requirements And Loading",
    "",
    "- Arma 3 version 2.18 or newer.",
    "- TRF UKAF and whichever TRF UKAF optional components you use.",
    "- Load this patch after TRF UKAF.",
    "- Component PBOs use `skipWhenMissingDependencies = 1`, allowing patches whose declared source dependency is absent to be skipped.",
    "",
    "## Exact Value Changes",
    "",
    "The values below are compared from HEMTT JSON output. `From` values come from the generated baseline snapshot cached under `source_addons/`; `To` values come from temporary patch configs with project-rooted macro includes resolved. Refresh the baseline after upstream updates.",
    "",
    "### Helmet Protection",
    "",
    markdownTable(changes.helmet),
    "",
    "### Vest Protection",
    "",
    markdownTable(changes.vest),
    "",
    "The source vest classes did not declare a `Neck` block. The patch adds one, but the effective inherited pre-patch values are unavailable and are not guessed here.",
    "",
    "### Eden And Zeus Visibility",
    "",
    markdownTable(changes.visibility),
    "",
    ...(changes.unknownScopeCurator.length === 0
      ? []
      : [
          `Every target explicitly declared \`scope = 2\` upstream. The ${changes.unknownScopeCurator.length} classes listed below did not explicitly declare \`scopeCurator\`; their inherited pre-patch value is unavailable.`,
          "",
          "```text",
          ...changes.unknownScopeCurator,
          "```",
          ""
        ]),
    "## Complete Addon Breakdown",
    "",
    ...addonSections,
    "",
    "## Building And Documentation",
    "",
    "```bash",
    "hemtt check",
    "hemtt dev",
    "hemtt release",
    "bun run docs",
    "bun run docs:refresh",
    "bun run docs:check",
    "```",
    "",
    "`bun run docs` regenerates this file and `WORKSHOP.md` from converted patch configs, creating the ignored baseline cache under `source_addons/` when needed. `bun run docs:refresh` first rebuilds the baseline from the extracted configs. `bun run docs:check` exits with an error when either generated file is stale.",
    "",
    "## Source And Issues",
    "",
    `- Source: ${repositoryUrl}`,
    `- Issues: ${repositoryUrl}/issues`,
    ""
  ].join("\n");
}

function workshopChanges(changes: ConfigComparison["helmet"]): string {
  const lines = changes
    .filter((change) => change.property !== "hitpointName")
    .map((change) => {
      const from = change.from === UNKNOWN_VALUE ? "inherited/unavailable" : change.from;
      const qualifier = change.status.includes("unchanged") ? " (unchanged)" : "";
      return `${change.area}.${change.property}: ${from} -> ${change.to}${qualifier}`;
    });
  return ["[code]", ...lines, "[/code]"].join("\n");
}

function workshopClassList(label: string, classes: string[]): string {
  if (classes.length === 0) {
    return "";
  }
  return [`[b]${label} (${classes.length})[/b]`, "[code]", ...classes, "[/code]", ""].join("\n");
}

function renderWorkshop(addons: AddonPatch[], changes: ConfigComparison): string {
  const helmets = addons.flatMap((addon) => addon.helmet);
  const vests = addons.flatMap((addon) => addon.vest);
  const hiddenDeclarations = addons.flatMap((addon) => addon.hidden);
  const uniqueHidden = new Set(hiddenDeclarations);
  const duplicateHidden = hiddenDeclarations.length - uniqueHidden.size;
  const insigniaClasses = new Set(addons.find((addon) => addon.directory === "trf_ukaf_insignia")?.hidden ?? []);
  const addonSections = addons
    .filter((addon) => addon.helmet.length + addon.vest.length + addon.hidden.length > 0)
    .map((addon) => {
      const heading = addon.displayName.replace("PJHQ Patches - ", "");
      const overlappingHidden = addon.hidden.filter((className) => insigniaClasses.has(className));
      const hidden = addon.directory === "trf_ukaf_pcs_insignia" ? addon.hidden.filter((className) => !insigniaClasses.has(className)) : addon.hidden;
      const overlapNote = addon.directory === "trf_ukaf_pcs_insignia" ? `Also patches all ${overlappingHidden.length} PCS classes listed under UKAF Insignia, plus:` : "";
      return [
        `[h2]${heading}[/h2]`,
        workshopClassList("Helmet armor", addon.helmet),
        workshopClassList("Vest armor", addon.vest),
        overlapNote,
        workshopClassList(addon.directory === "trf_ukaf_pcs_insignia" ? "Additional hidden classes" : "Hidden from Eden/Zeus placement", hidden)
      ]
        .filter((part) => part !== "")
        .join("\n");
    });

  return [
    "[h1]PJHQ Patch - TRF UKAF[/h1]",
    "A config-only compatibility and balance patch for TRF UKAF. It normalizes armor protection and cleans soldier gear proxy classes out of Eden and Zeus placement.",
    "",
    "[h1]Summary[/h1]",
    "[list]",
    `[*]Rebalances ${helmets.length} helmets and ${vests.length} vests.`,
    `[*]Hides ${uniqueHidden.size} unique classes from Eden/Zeus placement (${hiddenDeclarations.length} component declarations, including ${duplicateHidden} overlapping PCS proxy declarations).`,
    "[*]Leaves scopeArsenal unchanged, so source gear remains available in the Arsenal.",
    "[*]Changes config values only; no models, textures, sounds, scripts or event handlers are replaced.",
    "[/list]",
    "",
    "[h1]Requirements And Loading[/h1]",
    "[list]",
    "[*]Arma 3 version 2.18 or newer.",
    "[*]TRF UKAF and whichever TRF UKAF optional components you use.",
    "[*]Load this patch after TRF UKAF.",
    "[*]Patch components whose declared source dependency is missing are skipped.",
    "[/list]",
    "",
    "[h1]Exact Value Changes[/h1]",
    "[h2]Helmet Protection[/h2]",
    workshopChanges(changes.helmet),
    "",
    "[h2]Vest Protection[/h2]",
    workshopChanges(changes.vest),
    "",
    "The source vests did not declare a Neck block. This patch adds one; inherited pre-patch Neck values are unavailable and are not guessed.",
    "",
    "[h2]Eden And Zeus Visibility[/h2]",
    workshopChanges(changes.visibility),
    "",
    ...(changes.unknownScopeCurator.length === 0 ? [] : ["[code]", ...changes.unknownScopeCurator, "[/code]", ""]),
    "[h1]Complete Patch List[/h1]",
    ...addonSections,
    "",
    "[h1]Source And Support[/h1]",
    `[url=${repositoryUrl}]Source code and full README[/url]`,
    `[url=${repositoryUrl}/issues]Report an issue[/url]`,
    ""
  ].join("\n");
}

async function updateFile(fileName: string, content: string, checkOnly: boolean): Promise<boolean> {
  const filePath = path.join(root, fileName);
  const normalized = `${content.trimEnd()}\n`;
  if (checkOnly) {
    const existing = await readFile(filePath, "utf8").catch(() => "");
    if (existing.replaceAll("\r\n", "\n") !== normalized) {
      console.error(`${fileName} is out of date. Run: bun run docs`);
      return false;
    }
    return true;
  }

  await writeFile(filePath, normalized, "utf8");
  console.log(`Generated ${fileName}`);
  return true;
}

async function main(): Promise<void> {
  const checkOnly = process.argv.includes("--check");
  const refreshBaselines = process.argv.includes("--refresh-baselines");
  const addons = await readAddons();
  const changes = await compareConfigs(root, addons, refreshBaselines);

  const results = await Promise.all([updateFile("README.md", renderReadme(addons, changes), checkOnly), updateFile("WORKSHOP.md", renderWorkshop(addons, changes), checkOnly)]);
  if (results.some((result) => !result)) {
    process.exitCode = 1;
  }
}

await main();
